[phases.setup]
nixPkgs = ['ruby_3_1', 'libyaml-dev']

[phases.install]
cmds = ['bundle install --without development:test']

[phases.build]
cmds = ['RAILS_ENV=production bundle exec rails assets:precompile']

[start]
cmd = 'bundle exec puma -C config/puma.rb'
