[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'libyaml-dev', 'pkg-config', 'gcc', 'make']

[phases.install]
cmds = ['bundle install --without development test']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec puma -C config/puma.rb'
