[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'libyaml', 'pkg-config']

[phases.install]
cmds = ['bundle config build.psych --with-libyaml-dir=/nix/store/*libyaml*', 'bundle install']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile',
  'bundle exec rails db:mongoid:create_indexes'
]

[start]
cmd = 'bundle exec puma -C config/puma.rb'
