[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['bundle install']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile',
  'bundle exec rails db:mongoid:create_indexes'
]

[start]
cmd = 'bundle exec puma -C config/puma.rb'
